[package]
name = "features-deploy"
version = "0.1.0"
edition = "2021"

[dependencies]
core-plan = { path = "../../core/plan" }
core-config = { path = "../../core/config" }
core-path = { path = "../../core/path" }
